# Generated by Django 5.1.4 on 2025-01-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('company_admin', 'company_admin'), ('company_yonetici', 'company_yonetici'), ('company_muhasebeci', 'company_muhasebeci'), ('company_employee', 'company_employee'), ('company_rezervasyoncu', 'company_rezervasyoncu'), ('company_operasyoncu', 'company_operasyoncu'), ('company_driver', 'company_driver')], default='company_employee', max_length=50),
        ),
        migrations.DeleteModel(
            name='AccountRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
