# Generated by Django 5.1.4 on 2025-01-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('company_admin', 'Admin'), ('company_yonetici', 'Yönetici'), ('company_rezervasyoncu', 'Rezervasyoncu'), ('company_employee', 'Çalışan')], default='company_employee', max_length=50),
        ),
    ]
