# Generated by Django 5.1.4 on 2025-10-29 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_client',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_company_user',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('company_admin', 'Admin'), ('company_yonetici', 'Yönetici'), ('company_rezervasyoncu', 'Rezervasyoncu'), ('company_employee', 'Çalışan')], default='company_employee', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(default='en', max_length=2)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
