version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      # - cd frontend
      - npm run build -- --configuration development
  post_build:
    commands:

      # Sync other files with longer cache duration
      - aws s3 sync ./dist/airporttransfer/browser s3://airporttransferhub.com --exclude "index.html" --delete --cache-control "max-age=86400,immutable"

      # Copy HTML with short cache duration
      - aws s3 cp ./dist/airporttransfer/browser/index.html s3://airporttransferhub.com/index.html --cache-control "max-age=0,no-cache,no-store,must-revalidate"

      # Copy sitemap.xml and robots.txt to the root of the bucket with 1 day cache
      - aws s3 cp ./sitemap.xml s3://airporttransferhub.com/sitemap.xml --cache-control "max-age=86400, public"
      - aws s3 cp ./robots.txt s3://airporttransferhub.com/robots.txt --cache-control "max-age=86400, public"
      
      # Invalidate CloudFront
      - aws cloudfront create-invalidation --distribution-id EFE0BEJMOHTXL --paths "/*"
