# Generated by Django 5.1.4 on 2025-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_slug_alter_blogtag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqlibraryitem',
            name='slug_lock',
            field=models.BooleanField(default=False, help_text='Freeze the key from auto-regeneration'),
        ),
    ]
