# Generated by Django 5.1.4 on 2025-11-21 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_faqlibraryitem_slug_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('ru', 'Russian'), ('tr', 'Turkish')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.blogcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'language'], name='blog_blogca_categor_02e5c0_idx')],
                'unique_together': {('category', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BlogTagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('ru', 'Russian'), ('tr', 'Turkish')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.blogtag')),
            ],
            options={
                'indexes': [models.Index(fields=['tag', 'language'], name='blog_blogta_tag_id_7ca4e1_idx')],
                'unique_together': {('tag', 'language')},
            },
        ),
    ]
