export const SUPPORTED_MAIN_LOCATIONS = [
    { 
        code: 'AYT', 
        name: 'Antalya Airport Transfer', 
        value: '0',
        en: 'Antalya Airport Transfer',
        tr: 'Antalya Havalimanı Transfer',
        ru: 'Аэропорт Антальи Трансфер',
        fr: 'Aéroport d\'Antalya Transfert',
        de: 'Flughafen Antalya Transfer',
        hl: 'Luchthaven Antalya Transfer', 
    }, 
    {
        code: 'IST',
        name: 'Istanbul Airport Transfer',
        value: '1',
        en: 'Istanbul Airport Transfer',
        tr: 'İstanbul Havalimanı Transfer',
        ru: 'Аэропорт Стамбул Трансфер',
        fr: 'Aéroport d\'Istanbul Transfert',
        de: 'Flughafen Istanbul Transfer',
        hl: 'Luchthaven Istanbul Transfer',
    },
    {
        code: 'SAW',
        name: 'Sabiha Gokcen Airport Transfer',
        value: '2',
        en: 'Sabiha Gokcen Airport Transfer',
        tr: 'Sabiha Gökçen Havalimanı Transfer',
        ru: 'Аэропорт Сабиха Гокчен Трансфер',
        fr: 'Aéroport de Sabiha Gokcen Transfert',
        de: 'Flughafen Sabiha Gokcen Transfer',
        hl: 'Luchthaven Sabiha Gokcen Transfer',
    },
    {
        code: 'GZP',
        name: 'Gazipasa Airport Transfer',
        value: '3',
        en: 'Gazipasa Airport Transfer',
        tr: 'Gazipaşa Havalimanı Transfer',
        ru: 'Аэропорт Газипаша Трансфер',
        fr: 'Aéroport de Gazipasa Transfert',
        de: 'Flughafen Gazipasa Transfer',
        hl: 'Luchthaven Gazipasa Transfer',
    },
    {
        code: 'ESB',
        name: 'Ankara Esenboga Airport Transfer',
        value: '4',
        en: 'Ankara Esenboga Airport Transfer',
        tr: 'Ankara Esenboga Havalimanı Transfer',
        ru: 'Аэропорт Анкара Эсенбога Трансфер',
        fr: 'Aéroport d\'Ankara Esenboga Transfert',
        de: 'Flughafen Ankara Esenboga Transfer',
        hl: 'Luchthaven Ankara Esenboga Transfer',
    },
    {
        code: 'ADB',
        name: 'Izmir Adnan Menderes Airport Transfer',
        value: '5',
        en: 'Izmir Adnan Menderes Airport Transfer',
        tr: 'İzmir Adnan Menderes Havalimanı Transfer',
        ru: 'Аэропорт Измир Аднан Мендерес Трансфер',
        fr: 'Aéroport d\'Izmire Adnan Menderes Transfert',
        de: 'Flughafen Izmir Adnan Menderes Transfer',
        hl: 'Luchthaven Izmir Adnan Menderes Transfer',
    },
    {
        code: 'BJV',
        name: 'Bodrum Milas Airport Transfer',
        value: '6',
        en: 'Bodrum Milas Airport Transfer',
        tr: 'Bodrum Milas Havalimanı Transfer',
        ru: 'Аэропорт Бодрум Милас Трансфер',
        fr: 'Aéroport de Bodrum Milas Transfert',
        de: 'Flughafen Bodrum Milas Transfer',
        hl: 'Luchthaven Bodrum Milas Transfer',
    },
    {
        code: 'DLM',
        name: 'Dalaman Airport Transfer',
        value: '7',
        en: 'Dalaman Airport Transfer',
        tr: 'Dalaman Havalimanı Transfer',
        ru: 'Аэропорт Даламан Трансфер',
        fr: 'Aéroport de Dalaman Transfert',
        de: 'Flughafen Dalaman Transfer',
        hl: 'Luchthaven Dalaman Transfer',
    }, 
];
