# Generated by Django 5.1.4 on 2025-01-10 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency_code', models.CharField(max_length=3)),
                ('reservation_date', models.DateField(default=datetime.date(2025, 1, 10))),
                ('car_type', models.CharField(max_length=255)),
                ('transfer_date', models.DateField(blank=True, default=datetime.date(2025, 1, 10), null=True)),
                ('transfer_time', models.TimeField(blank=True, null=True)),
                ('transfer_date_time', models.DateTimeField(blank=True, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=25, null=True)),
                ('flight_date', models.DateField(blank=True, null=True)),
                ('flight_time', models.TimeField(blank=True, null=True)),
                ('flight_date_time', models.DateTimeField(blank=True, null=True)),
                ('passenger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('passenger_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('passenger_email', models.CharField(blank=True, max_length=255, null=True)),
                ('passenger_count', models.IntegerField(blank=True, default=1, null=True)),
                ('passenger_count_child', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_round_trip', models.BooleanField(default=False)),
                ('pickup_short', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_full', models.CharField(blank=True, max_length=1024, null=True)),
                ('dest_short', models.CharField(blank=True, max_length=255, null=True)),
                ('dest_full', models.CharField(blank=True, max_length=1024, null=True)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('need_child_seat', models.BooleanField(default=False)),
                ('child_seat_count', models.IntegerField(default=0)),
                ('need_greet_sign', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transfer_date', 'transfer_time'],
            },
        ),
    ]
