# Generated by Django 5.1.4 on 2025-01-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_reservation_distance_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='dest_lon',
            new_name='dest_lng',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='pickup_lon',
            new_name='pickup_lng',
        ),
    ]
