# Generated by Django 5.1.4 on 2025-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_rename_dest_lon_reservation_dest_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='distance_km',
            new_name='distance',
        ),
        migrations.AddField(
            model_name='reservation',
            name='driving_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
