# Generated by Django 5.1.4 on 2025-01-27 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_contactusmessage_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='need_greet_sign',
        ),
        migrations.AddField(
            model_name='reservation',
            name='greet_with_champagne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='greet_with_flower',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=datetime.date(2025, 1, 27)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 27), null=True),
        ),
    ]
