# Generated by Django 5.1.4 on 2025-05-01 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0018_reservation_direction_type_reservation_transfer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', '-transfer_date', 'transfer_time']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=datetime.date(2025, 5, 1)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 1), null=True),
        ),
    ]
