# Generated by Django 5.1.4 on 2025-05-11 11:58

import datetime
import transfer.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0019_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=transfer.utils.get_local_date),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 11), null=True),
        ),
    ]
