# Generated by Django 5.1.4 on 2025-05-17 11:15

import transfer.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0020_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date', '-transfer_date', 'transfer_time']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='car_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='transfer_date',
            field=models.DateField(blank=True, default=transfer.utils.get_local_date, null=True),
        ),
    ]
