# Generated by Django 5.1.4 on 2025-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0021_alter_reservation_options_alter_reservation_car_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
