# Generated by Django 5.1.4 on 2025-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0022_alter_reservation_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial_refund', 'Partially Refunded'), ('refunded', 'Refunded')], default='unpaid', max_length=32),
        ),
    ]
