# Generated by Django 5.1.4 on 2025-11-03 05:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def normalize_reservation_statuses(apps, schema_editor):
    Reservation = apps.get_model('transfer', 'Reservation')
    Reservation.objects.filter(status='pending').update(status='draft')
    Reservation.objects.filter(status='inoperation').update(status='confirmed')


def revert_reservation_statuses(apps, schema_editor):
    Reservation = apps.get_model('transfer', 'Reservation')
    Reservation.objects.filter(status='draft').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0023_reservation_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_reservation_statuses, revert_reservation_statuses),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_by_operator', 'Cancelled by Operator'), ('no_show', 'No Show')], default='draft', max_length=64),
        ),
        migrations.CreateModel(
            name='ReservationChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('auto_approved', 'Auto Approved'), ('awaiting_user_payment', 'Awaiting User Payment'), ('approved_applied', 'Approved & Applied'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_review', max_length=64)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('applied_changes', models.JSONField(blank=True, default=dict)),
                ('pricing_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cutoff_ok', models.BooleanField(default=True)),
                ('requires_manual_review', models.BooleanField(default=True)),
                ('reason_code', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_change_requests', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_change_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='transfer.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('reservation', 'idempotency_key'), name='unique_change_request_idempotency_key')],
            },
        ),
    ]
