# Generated by Django 5.1.4 on 2025-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularroute',
            name='car_type',
            field=models.CharField(choices=[('VITO', 'Mercedes Vito'), ('SPRINTER', 'Mercedes Sprinter'), ('MAYBACH', 'Mercedes Maybach S class'), ('MINIBUS', 'Minibus')], default='VITO', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eurorate',
            name='currency_code',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('GBP', '£')], max_length=3),
        ),
        migrations.AlterField(
            model_name='popularroute',
            name='main_location',
            field=models.CharField(choices=[('AYT', 'Antalya Airport Transfer'), ('DLM', 'Dalaman Airport Transfer'), ('IST', 'Istanbul Airport Transfer'), ('SAW', 'Sabiha Gokcen Airport Transfer'), ('ESB', 'Ankara Esenboga Airport Transfer'), ('ADB', 'Izmir Adnan Menderes Airport Transfer'), ('BJV', 'Bodrum Milas Airport Transfer'), ('GZP', 'Gazipasa Airport Transfer')], max_length=10),
        ),
    ]
