# Generated by Django 5.1.4 on 2025-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_popularroute_car_type_alter_eurorate_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurorate',
            name='currency_code',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('GBP', '£')], max_length=3, unique=True),
        ),
    ]
