# Generated by Django 5.1.4 on 2025-01-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_eurorate_currency_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularroute',
            old_name='to',
            new_name='destination',
        ),
        migrations.AlterUniqueTogether(
            name='popularroute',
            unique_together={('main_location', 'destination', 'car_type')},
        ),
    ]
