# Generated by Django 5.1.4 on 2025-11-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_airport_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='eurorate',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='common.currency'),
        ),
        migrations.AddField(
            model_name='popularroute',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_routes', to='common.airport'),
        ),
        migrations.AlterField(
            model_name='eurorate',
            name='currency_code',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('GBP', '£'), ('RUB', '₽'), ('TRY', '₺')], max_length=3, unique=True),
        ),
    ]
