# Generated by Django 5.1.4 on 2025-11-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_eurorate_currency_popularroute_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularroute',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='popular_routes', to='common.airport'),
        ),
    ]
