# Generated by Django 5.1.4 on 2025-11-06 04:54

import django.contrib.postgres.fields
import django.db.models.deletion
import payment.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_ref', models.CharField(db_index=True, max_length=64)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('RUB_PHONE_TRANSFER', 'Rub Phone Transfer'), ('CARD', 'Card')], max_length=32)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='requires_payment_method', max_length=32)),
                ('provider', models.CharField(max_length=32)),
                ('provider_intent_id', models.CharField(blank=True, max_length=128, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capture_method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=16)),
                ('return_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=payment.models.default_json)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_payments', 'Can manage and settle payments')],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('offline', 'Offline'), ('stripe', 'Stripe'), ('iyzico', 'Iyzico'), ('paytr', 'Paytr')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('default_currency', models.CharField(max_length=3)),
                ('supported_currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, default=list, size=None)),
                ('metadata', models.JSONField(blank=True, default=payment.models.default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment provider account',
                'verbose_name_plural': 'Payment provider accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_id', models.CharField(max_length=128, unique=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('failed', 'Failed')], max_length=32)),
                ('card_brand', models.CharField(blank=True, max_length=32, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refundable_minor', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=payment.models.default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment.paymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_file', models.FileField(upload_to=payment.models.offline_receipt_upload_to)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_offline_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_receipts', to='payment.paymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransferInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=64)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('reference_text', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_instruction', to='payment.paymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intents', to='payment.paymentprovideraccount'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.BigIntegerField()),
                ('provider_refund_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=payment.models.default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('intent_created', 'Intent Created'), ('intent_updated', 'Intent Updated'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('refund_requested', 'Refund Requested'), ('refund_succeeded', 'Refund Succeeded'), ('refund_failed', 'Refund Failed'), ('offline_receipt_submitted', 'Offline Receipt Submitted')], max_length=64)),
                ('booking_ref', models.CharField(max_length=64)),
                ('delta_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('snapshot', models.JSONField(blank=True, default=payment.models.default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='payment.payment')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='payment.paymentintent')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='payment.refund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_intent_id__isnull', False)), fields=('provider', 'provider_intent_id'), name='unique_provider_intent', violation_error_message='Provider intent already registered.'),
        ),
    ]
