# Generated by Django 5.1.4 on 2025-11-19 10:21

import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_banktransferinstruction_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('RUB_PHONE_TRANSFER', 'Rub Phone Transfer'), ('CARD', 'Card')], max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('swift_code', models.CharField(blank=True, max_length=64)),
                ('branch_code', models.CharField(blank=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('reference_hint', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=payment.models.default_json)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority accounts are used first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-priority', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='banktransferinstruction',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='banktransferinstruction',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='banktransferinstruction',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='banktransferinstruction',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='banktransferinstruction',
            name='metadata',
            field=models.JSONField(blank=True, default=payment.models.default_json),
        ),
        migrations.AddField(
            model_name='banktransferinstruction',
            name='bank_accounts',
            field=models.ManyToManyField(blank=True, related_name='bank_transfer_instructions', to='payment.paymentbankaccount'),
        ),
    ]
