import logging
from decimal import Decimal
from typing import Optional

from django.conf import settings
from django.utils import timezone
from django.db import models

from .utils import (
    get_autogenerated_reservation_number, 
    get_local_date, get_local_time, 
)


logger = logging.getLogger('airporttransfer')


class ReservationStatus(models.TextChoices):
    DRAFT = 'draft', 'Draft'
    AWAITING_PAYMENT = 'awaiting_payment', 'Awaiting Payment'
    CONFIRMED = 'confirmed', 'Confirmed'
    COMPLETED = 'completed', 'Completed'
    CANCELLED_BY_USER = 'cancelled_by_user', 'Cancelled by User'
    CANCELLED_BY_OPERATOR = 'cancelled_by_operator', 'Cancelled by Operator'
    NO_SHOW = 'no_show', 'No Show'


class Reservation(models.Model):

    PAYMENT_STATUS_CHOICES = [
        ('unpaid', 'Unpaid'),
        ('paid', 'Paid'),
        ('partial_refund', 'Partially Refunded'),
        ('refunded', 'Refunded'),
    ]

    TRANSFER_TYPE_CHOICES = [
        ('PRIVATE', 'Özel Transfer'),
        ('SHUTTLE', 'Paylaşımlı Transfer'),
    ]
    DIRECTION_TYPE_CHOICES = [
        ('ARR', 'Arrival'),
        ('DEP', 'Departure'),
        ('ARA', 'Round Trip'),
    ]

    number = models.CharField(max_length=255, null=True, blank=True)
    
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    currency_code = models.CharField(max_length=3, null=True, blank=True)
    is_nakit = models.BooleanField(default=True)

    reservation_date = models.DateField(default=get_local_date)

    transfer_type = models.CharField(max_length=255, choices=TRANSFER_TYPE_CHOICES, default='PRIVATE', null=True, blank=True)
    direction_type = models.CharField(max_length=255, choices=DIRECTION_TYPE_CHOICES, default='ARR', null=True, blank=True)
    car_type = models.CharField(max_length=255, null=True, blank=True)

    transfer_date = models.DateField(null=True, blank=True)
    transfer_time = models.TimeField(null=True, blank=True)
    transfer_date_time = models.DateTimeField(null=True, blank=True)
    flight_number = models.CharField(max_length=25, null=True, blank=True)
    flight_date = models.DateField(null=True, blank=True)
    flight_time = models.TimeField(null=True, blank=True)
    flight_date_time = models.DateTimeField(null=True, blank=True)

    passenger_name = models.CharField(max_length=255, null=True, blank=True)
    passenger_phone = models.CharField(max_length=255, null=True, blank=True)
    passenger_email = models.CharField(max_length=255, null=True, blank=True)
    passenger_count = models.IntegerField(default=1, null=True, blank=True)
    passenger_count_child = models.IntegerField(default=0, null=True, blank=True)
    note = models.TextField(blank=True, null=True)

    is_round_trip = models.BooleanField(default=False)

    pickup_short = models.CharField(max_length=255, null=True, blank=True)
    pickup_full = models.CharField(max_length=1024, null=True, blank=True)
    dest_short = models.CharField(max_length=255, null=True, blank=True)
    dest_full = models.CharField(max_length=1024, null=True, blank=True)
    pickup_lat = models.DecimalField(max_digits=20, decimal_places=15, null=True, blank=True)
    pickup_lng = models.DecimalField(max_digits=20, decimal_places=15, null=True, blank=True)
    dest_lat = models.DecimalField(max_digits=20, decimal_places=15, null=True, blank=True)
    dest_lng = models.DecimalField(max_digits=20, decimal_places=15, null=True, blank=True)
    distance = models.DecimalField(max_digits=20, decimal_places=10, null=True, blank=True)
    driving_duration = models.IntegerField(null=True, blank=True)
    
    # Extra services
    need_child_seat = models.BooleanField(default=False)
    child_seat_count = models.IntegerField(default=0)
    
    greet_with_champagne = models.BooleanField(default=False)
    greet_with_flower = models.BooleanField(default=False)
    
    status = models.CharField(
        max_length=64,
        choices=ReservationStatus.choices,
        default=ReservationStatus.DRAFT,
    )
    payment_status = models.CharField(max_length=32, choices=PAYMENT_STATUS_CHOICES, default='unpaid')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-reservation_date', '-transfer_date', 'transfer_time']

    def save(self, *args, **kwargs):
        logger.debug(f"Inside Reservation save: {self.id}")
                
        # Handle date time fields
        if self.transfer_date and self.transfer_time:
            naive_transfer_datetime = timezone.datetime.combine(self.transfer_date, self.transfer_time)
            if not timezone.is_aware(naive_transfer_datetime):
                self.transfer_date_time = timezone.make_aware(naive_transfer_datetime)
            else:
                self.transfer_date_time = naive_transfer_datetime

        if self.flight_date and self.flight_time:
            naive_flight_datetime = timezone.datetime.combine(self.flight_date, self.flight_time)
            if not timezone.is_aware(naive_flight_datetime):
                self.flight_date_time = timezone.make_aware(naive_flight_datetime)
            else:
                self.flight_date_time = naive_flight_datetime
        
        # Handle decimal amounts
        if not isinstance(self.amount, Decimal):
            self.amount = Decimal(self.amount)

        # If need_child_seat is False, set child_seat_count to 0
        if not self.need_child_seat:
            self.child_seat_count = 0
        
        if not self.number:
            self.number = get_autogenerated_reservation_number(company_code='ATH')

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.transfer_date} - [{self.pickup_short}-{self.dest_short}] - {self.transfer_time}"


class ReservationPassenger(models.Model):
    reservation = models.ForeignKey(
        Reservation,
        related_name='passengers',
        on_delete=models.CASCADE,
    )
    full_name = models.CharField(max_length=255)
    is_child = models.BooleanField(default=False)
    order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['order', 'id']
        constraints = [
            models.UniqueConstraint(
                fields=['reservation', 'order'],
                name='unique_passenger_order_per_reservation',
            ),
        ]

    def __str__(self):
        return f"{self.full_name} ({'Child' if self.is_child else 'Adult'})"


class ReservationChangeRequestStatus(models.TextChoices):
    PENDING_REVIEW = 'pending_review', 'Pending Review'
    AUTO_APPROVED = 'auto_approved', 'Auto Approved'
    AWAITING_USER_PAYMENT = 'awaiting_user_payment', 'Awaiting User Payment'
    APPROVED_APPLIED = 'approved_applied', 'Approved & Applied'
    DECLINED = 'declined', 'Declined'
    EXPIRED = 'expired', 'Expired'
    CANCELLED = 'cancelled', 'Cancelled'


class ReservationChangeRequest(models.Model):
    reservation = models.ForeignKey(
        'transfer.Reservation',
        related_name='change_requests',
        on_delete=models.CASCADE,
    )
    status = models.CharField(
        max_length=64,
        choices=ReservationChangeRequestStatus.choices,
        default=ReservationChangeRequestStatus.PENDING_REVIEW,
    )
    proposed_changes = models.JSONField(default=dict, blank=True)
    applied_changes = models.JSONField(default=dict, blank=True)
    pricing_delta = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    cutoff_ok = models.BooleanField(default=True)
    requires_manual_review = models.BooleanField(default=True)
    reason_code = models.CharField(max_length=255, blank=True)
    idempotency_key = models.CharField(max_length=64, blank=True, null=True)
    expires_at = models.DateTimeField(blank=True, null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='reservation_change_requests',
        on_delete=models.PROTECT,
    )
    decided_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='reservation_change_requests_decided',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    decided_at = models.DateTimeField(null=True, blank=True)
    decision_reason = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        constraints = [
            models.UniqueConstraint(
                fields=['reservation', 'idempotency_key'],
                name='unique_change_request_idempotency_key',
                condition=models.Q(idempotency_key__isnull=False),
            ),
        ]

    def mark_declined(self, actor, reason: Optional[str] = None) -> None:
        self.status = ReservationChangeRequestStatus.DECLINED
        self.decision_reason = reason or ''
        self.decided_by = actor
        self.decided_at = timezone.now()
        self.save(update_fields=['status', 'decision_reason', 'decided_by', 'decided_at', 'updated_at'])

    def __str__(self) -> str:
        return f"CR#{self.pk} for Reservation {self.reservation_id} ({self.status})"


class ContactUsMessage(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} - {self.email}"
    

# class Callback(models.Model):
#     CALLBACK_TYPE_CHOICES = [
#         ('new_reservation', 'Yeni Rezervasyon'),
#         ('change_reservation', 'Rezervasyon Değişikliği')
#     ]
#     callback_type = models.CharField(max_length=255, choices=CALLBACK_TYPE_CHOICES)
#     url = models.URLField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     class Meta:
#         ordering = ['-created_at']
#         constraints = [
#             models.UniqueConstraint(fields=['callback_type', 'url'], name='unique_callback')
#         ]
