name: CI Workflow

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend 
          pip3 install -r requirements.txt
      - name: Run tests
        run: |
          cd backend
          python3 manage.py test --settings=yourproject.settings_test
